' --------------------------------------------------------------------
' Geodesix
' Copyright © 2024 Maurice Calvert
' 
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
' 
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
' 
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <http://www.gnu.org/licenses/>.
' --------------------------------------------------------------------
Public Module GoogleRegions_
    Public ReadOnly Property GoogleRegions As New List(Of Pair) From {
        New Pair("Afghanistan", "AF"),
        New Pair("Åland Islands", "AX"),
        New Pair("Albania", "AL"),
        New Pair("Algeria", "DZ"),
        New Pair("American Samoa", "AS"),
        New Pair("Andorra", "AD"),
        New Pair("Angola", "AO"),
        New Pair("Anguilla", "AI"),
        New Pair("Antarctica", "AQ"),
        New Pair("Antigua & Barbuda", "AG"),
        New Pair("Argentina", "AR"),
        New Pair("Armenia", "AM"),
        New Pair("Aruba", "AW"),
        New Pair("Ascension Island", "AC"),
        New Pair("Australia", "AU"),
        New Pair("Austria", "AT"),
        New Pair("Azerbaijan", "AZ"),
        New Pair("Bahamas", "BS"),
        New Pair("Bahrain", "BH"),
        New Pair("Bangladesh", "BD"),
        New Pair("Barbados", "BB"),
        New Pair("Belarus", "BY"),
        New Pair("Belgium", "BE"),
        New Pair("Belize", "BZ"),
        New Pair("Benin", "BJ"),
        New Pair("Bermuda", "BM"),
        New Pair("Bhutan", "BT"),
        New Pair("Bolivia", "BO"),
        New Pair("Bosnia & Herzegovina", "BA"),
        New Pair("Botswana", "BW"),
        New Pair("Bouvet Island", "BV"),
        New Pair("Brazil", "BR"),
        New Pair("British Indian Ocean Territory", "IO"),
        New Pair("British Virgin Islands", "VG"),
        New Pair("Brunei", "BN"),
        New Pair("Bulgaria", "BG"),
        New Pair("Burkina Faso", "BF"),
        New Pair("Burundi", "BI"),
        New Pair("Cambodia", "KH"),
        New Pair("Cameroon", "CM"),
        New Pair("Canada", "CA"),
        New Pair("Canary Islands", "IC"),
        New Pair("Cape Verde", "CV"),
        New Pair("Caribbean Netherlands", "BQ"),
        New Pair("Cayman Islands", "KY"),
        New Pair("Central African Republic", "CF"),
        New Pair("Ceuta & Melilla", "EA"),
        New Pair("Chad", "TD"),
        New Pair("Chile", "CL"),
        New Pair("China", "CN"),
        New Pair("Christmas Island", "CX"),
        New Pair("Clipperton Island", "CP"),
        New Pair("Cocos (Keeling) Islands", "CC"),
        New Pair("Colombia", "CO"),
        New Pair("Comoros", "KM"),
        New Pair("Congo - Brazzaville", "CG"),
        New Pair("Congo - Kinshasa", "CD"),
        New Pair("Cook Islands", "CK"),
        New Pair("Costa Rica", "CR"),
        New Pair("Côte d’Ivoire", "CI"),
        New Pair("Croatia", "HR"),
        New Pair("Cuba", "CU"),
        New Pair("Curaçao", "CW"),
        New Pair("Cyprus", "CY"),
        New Pair("Czechia", "CZ"),
        New Pair("Denmark", "DK"),
        New Pair("Diego Garcia", "DG"),
        New Pair("Djibouti", "DJ"),
        New Pair("Dominica", "DM"),
        New Pair("Dominican Republic", "DO"),
        New Pair("Ecuador", "EC"),
        New Pair("Egypt", "EG"),
        New Pair("El Salvador", "SV"),
        New Pair("Equatorial Guinea", "GQ"),
        New Pair("Eritrea", "ER"),
        New Pair("Estonia", "EE"),
        New Pair("Eswatini", "SZ"),
        New Pair("Ethiopia", "ET"),
        New Pair("Falkland Islands (Islas Malvinas)", "FK"),
        New Pair("Faroe Islands", "FO"),
        New Pair("Fiji", "FJ"),
        New Pair("Finland", "FI"),
        New Pair("France", "FR"),
        New Pair("French Guiana", "GF"),
        New Pair("French Polynesia", "PF"),
        New Pair("French Southern Territories", "TF"),
        New Pair("Gabon", "GA"),
        New Pair("Gambia", "GM"),
        New Pair("Georgia", "GE"),
        New Pair("Germany", "DE"),
        New Pair("Ghana", "GH"),
        New Pair("Gibraltar", "GI"),
        New Pair("Greece", "GR"),
        New Pair("Greenland", "GL"),
        New Pair("Grenada", "GD"),
        New Pair("Guadeloupe", "GP"),
        New Pair("Guam", "GU"),
        New Pair("Guatemala", "GT"),
        New Pair("Guernsey", "GG"),
        New Pair("Guinea", "GN"),
        New Pair("Guinea-Bissau", "GW"),
        New Pair("Guyana", "GY"),
        New Pair("Haiti", "HT"),
        New Pair("Heard & McDonald Islands", "HM"),
        New Pair("Honduras", "HN"),
        New Pair("Hong Kong", "HK"),
        New Pair("Hungary", "HU"),
        New Pair("Iceland", "IS"),
        New Pair("India", "IN"),
        New Pair("Indonesia", "ID"),
        New Pair("Iran", "IR"),
        New Pair("Iraq", "IQ"),
        New Pair("Ireland", "IE"),
        New Pair("Isle of Man", "IM"),
        New Pair("Israel", "IL"),
        New Pair("Italy", "IT"),
        New Pair("Jamaica", "JM"),
        New Pair("Japan", "JP"),
        New Pair("Jersey", "JE"),
        New Pair("Jordan", "JO"),
        New Pair("Kazakhstan", "KZ"),
        New Pair("Kenya", "KE"),
        New Pair("Kiribati", "KI"),
        New Pair("Kosovo", "XK"),
        New Pair("Kuwait", "KW"),
        New Pair("Kyrgyzstan", "KG"),
        New Pair("Laos", "LA"),
        New Pair("Latvia", "LV"),
        New Pair("Lebanon", "LB"),
        New Pair("Lesotho", "LS"),
        New Pair("Liberia", "LR"),
        New Pair("Libya", "LY"),
        New Pair("Liechtenstein", "LI"),
        New Pair("Lithuania", "LT"),
        New Pair("Luxembourg", "LU"),
        New Pair("Macao", "MO"),
        New Pair("Madagascar", "MG"),
        New Pair("Malawi", "MW"),
        New Pair("Malaysia", "MY"),
        New Pair("Maldives", "MV"),
        New Pair("Mali", "ML"),
        New Pair("Malta", "MT"),
        New Pair("Marshall Islands", "MH"),
        New Pair("Martinique", "MQ"),
        New Pair("Mauritania", "MR"),
        New Pair("Mauritius", "MU"),
        New Pair("Mayotte", "YT"),
        New Pair("Mexico", "MX"),
        New Pair("Micronesia", "FM"),
        New Pair("Moldova", "MD"),
        New Pair("Monaco", "MC"),
        New Pair("Mongolia", "MN"),
        New Pair("Montenegro", "ME"),
        New Pair("Montserrat", "MS"),
        New Pair("Morocco", "MA"),
        New Pair("Mozambique", "MZ"),
        New Pair("Myanmar (Burma)", "MM"),
        New Pair("Namibia", "NA"),
        New Pair("Nauru", "NR"),
        New Pair("Nepal", "NP"),
        New Pair("Netherlands", "NL"),
        New Pair("New Caledonia", "NC"),
        New Pair("New Zealand", "NZ"),
        New Pair("Nicaragua", "NI"),
        New Pair("Niger", "NE"),
        New Pair("Nigeria", "NG"),
        New Pair("Niue", "NU"),
        New Pair("Norfolk Island", "NF"),
        New Pair("North Korea", "KP"),
        New Pair("North Macedonia", "MK"),
        New Pair("Northern Mariana Islands", "MP"),
        New Pair("Norway", "NO"),
        New Pair("Oman", "OM"),
        New Pair("Pakistan", "PK"),
        New Pair("Palau", "PW"),
        New Pair("Palestine", "PS"),
        New Pair("Panama", "PA"),
        New Pair("Papua New Guinea", "PG"),
        New Pair("Paraguay", "PY"),
        New Pair("Peru", "PE"),
        New Pair("Philippines", "PH"),
        New Pair("Pitcairn Islands", "PN"),
        New Pair("Poland", "PL"),
        New Pair("Portugal", "PT"),
        New Pair("Puerto Rico", "PR"),
        New Pair("Qatar", "QA"),
        New Pair("Réunion", "RE"),
        New Pair("Romania", "RO"),
        New Pair("Russia", "RU"),
        New Pair("Rwanda", "RW"),
        New Pair("Samoa", "WS"),
        New Pair("San Marino", "SM"),
        New Pair("São Tomé & Príncipe", "ST"),
        New Pair("Saudi Arabia", "SA"),
        New Pair("Senegal", "SN"),
        New Pair("Serbia", "RS"),
        New Pair("Seychelles", "SC"),
        New Pair("Sierra Leone", "SL"),
        New Pair("Singapore", "SG"),
        New Pair("Sint Maarten", "SX"),
        New Pair("Slovakia", "SK"),
        New Pair("Slovenia", "SI"),
        New Pair("Solomon Islands", "SB"),
        New Pair("Somalia", "SO"),
        New Pair("South Africa", "ZA"),
        New Pair("South Georgia & South Sandwich Islands", "GS"),
        New Pair("South Korea", "KR"),
        New Pair("South Sudan", "SS"),
        New Pair("Spain", "ES"),
        New Pair("Sri Lanka", "LK"),
        New Pair("St. Barthélemy", "BL"),
        New Pair("St. Helena", "SH"),
        New Pair("St. Kitts & Nevis", "KN"),
        New Pair("St. Lucia", "LC"),
        New Pair("St. Martin", "MF"),
        New Pair("St. Pierre & Miquelon", "PM"),
        New Pair("St. Vincent & Grenadines", "VC"),
        New Pair("Sudan", "SD"),
        New Pair("Suriname", "SR"),
        New Pair("Svalbard & Jan Mayen", "SJ"),
        New Pair("Sweden", "SE"),
        New Pair("Switzerland", "CH"),
        New Pair("Syria", "SY"),
        New Pair("Taiwan", "TW"),
        New Pair("Tajikistan", "TJ"),
        New Pair("Tanzania", "TZ"),
        New Pair("Thailand", "TH"),
        New Pair("Timor-Leste", "TL"),
        New Pair("Togo", "TG"),
        New Pair("Tokelau", "TK"),
        New Pair("Tonga", "TO"),
        New Pair("Trinidad & Tobago", "TT"),
        New Pair("Tristan da Cunha", "TA"),
        New Pair("Tunisia", "TN"),
        New Pair("Turkey", "TR"),
        New Pair("Turkmenistan", "TM"),
        New Pair("Turks & Caicos Islands", "TC"),
        New Pair("Tuvalu", "TV"),
        New Pair("U.S. Outlying Islands", "UM"),
        New Pair("U.S. Virgin Islands", "VI"),
        New Pair("Uganda", "UG"),
        New Pair("Ukraine", "UA"),
        New Pair("United Arab Emirates", "AE"),
        New Pair("United Kingdom", "GB"),
        New Pair("United States", "US"),
        New Pair("Uruguay", "UY"),
        New Pair("Uzbekistan", "UZ"),
        New Pair("Vanuatu", "VU"),
        New Pair("Vatican City", "VA"),
        New Pair("Venezuela", "VE"),
        New Pair("Vietnam", "VN"),
        New Pair("Wallis & Futuna", "WF"),
        New Pair("Western Sahara", "EH"),
        New Pair("Yemen", "YE"),
        New Pair("Zambia", "ZM"),
        New Pair("Zimbabwe", "ZW")
   }

End Module
